#!/usr/bin/env bash
# This script creates the file /var/run/myscript.pid containing its PID
# Displays To infinity and beyond indefinitely
# Displays I hate the kill command when receiving a SIGTERM signal
# Deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal

function terminate() {
    echo "I hate the kill command"
    rm /var/run/myscript.pid
    exit
}

trap "terminate" SIGTERM SIGQUIT

echo $$ > /var/run/myscript.pid

while true; do
    echo "To infinity and beyond"
    sleep 1
done
